/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hongkailiu' at '06/11/16 6:48 PM' with Gradle 2.13
 *
 * @author hongkailiu, @date 06/11/16 6:48 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
